apiVersion: v1
kind: ConfigMap
metadata:
  name: notifyhub-config
  labels:
    app.kubernetes.io/part-of: notifyhub
data:
  AUTH_JWT_ISSUER: notifyhub-auth
  AUTH_JWT_EXPIRATION: PT2H
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_ENABLED: "true"
  KAFKA_TOPIC_REMINDER_TRIGGERED: reminder.triggered
  KAFKA_NOTIFICATION_GROUP_ID: notification-service
  REMINDER_TRIGGER_SCHEDULER_ENABLED: "true"
  REMINDER_TRIGGER_SCHEDULER_DELAY_MS: "5000"
  RABBITMQ_ENABLED: "true"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  NOTIFICATION_DELIVERY_MAX_ATTEMPTS: "3"
  NOTIFICATION_DELIVERY_RETRY_DELAY_MS: "5000"
  AUTH_SERVICE_URL: http://auth-service:8081
  REMINDER_SERVICE_URL: http://reminder-service:8082
  NOTIFICATION_SERVICE_URL: http://notification-service:8083
  AUTH_DB_URL: jdbc:postgresql://postgres:5432/notifyhub_auth
  REMINDER_DB_URL: jdbc:postgresql://postgres:5432/notifyhub_reminder
  NOTIFICATION_DB_URL: jdbc:postgresql://postgres:5432/notifyhub_notification
