apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notifyhub

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - kafka.yaml
  - backend-services.yaml
  - dashboard.yaml
  - observability.yaml
