ALTER TABLE auth_users ADD COLUMN first_name VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE auth_users ADD COLUMN last_name VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE auth_users ADD COLUMN phone_number VARCHAR(32) NOT NULL DEFAULT '';
