input {
  gelf {
    port => 12201
    use_udp => true
  }
}

filter {
  mutate {
    add_field => {
      "[service][namespace]" => "notifyhub"
      "[event][dataset]" => "notifyhub.container"
      "[data_stream][type]" => "logs"
      "[data_stream][dataset]" => "notifyhub"
      "[data_stream][namespace]" => "local"
    }
  }

  if [container_name] {
    mutate {
      rename => { "container_name" => "[container][name]" }
    }
  }

  if [container_id] {
    mutate {
      rename => { "container_id" => "[container][id]" }
    }
  }

  if [image_name] {
    mutate {
      rename => { "image_name" => "[container][image][name]" }
    }
  }

  if [source_host] {
    mutate {
      rename => { "source_host" => "[host][name]" }
    }
  }

  if [short_message] and ![message] {
    mutate {
      rename => { "short_message" => "message" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "notifyhub"
    data_stream_namespace => "local"
  }
}
